// Supabase 설정
window.SUPABASE_URL = 'https://spwnipdqouprwgjxerdk.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwd25pcGRxb3VwcndnanhlcmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODk1MzMsImV4cCI6MjA3MTk2NTUzM30.ELPcfo3plC54xY1QDLS7wVjOImyIaew3hyAq_80TLOA';
